server:
    port: 8081
    context-path: /
    session:
        timeout: 3600
debug: true

email:
    port: 25
    address: yiluoye86@163.com



spring:
    jpa:
      show-sql: true
      hibernate:
        ddl-auto: create
    datasource:
       type: com.alibaba.druid.pool.DruidDataSource
       driver-class-name: com.mysql.jdbc.Driver
       url: jdbc:mysql://localhost:3306/test?useUnicode=true&characterEncoding=utf-8&useSSL=false
       username: root
       password: acedata1706
    http:
       encoding:
         charset: utf-8
         force: true
    thymeleaf:
      prefix: classpath:/templates/
      suffix: .html
      cache: false
      mode: HTML5