server:
    port: 8081
    context-path: /
    session:
        timeout: 3600
debug: true


spring:
    datasource:
       type: com.alibaba.druid.pool.DruidDataSource
       driver-class-name: com.mysql.jdbc.Driver
       url: jdbc:mysql://localhost:3306/test
       username: root
       password: acedata1706
    http:
       encoding:
         charset: utf-8
         force: true
    thymeleaf:
      prefix: classpath:/templates/
      suffix: .html
      cache: false
      mode: HTML5